"""ComfyUI V3 node that turns an LLM-generated prompt hint into a usable
diffusion prompt plus concrete image dimensions.

Input
-----
- ``llm_prompt`` (String): the JSON hint from the LLM, e.g.::

      {"rewritten_prompt": "...", "wh_ratio": "16:9", "ratio_follow": "<image1>"}

- ``megapixels`` (Float): target size in megapixels (0.1-16.0), used only when
  ``wh_ratio`` is present to derive an actual resolution.

- ``multiple`` (Int): pixel grid the resolved width/height are rounded up to
  (default 8). Only used when ``wh_ratio`` is present.

- ``images`` (Autogrow, up to 10): uploaded reference images. When
  ``ratio_follow`` names one of them, that image's pixel size is used verbatim.

Output
------
- ``prompt`` (String): the validated ``rewritten_prompt``.
- ``width`` / ``height`` (Int): resolved target dimensions.
"""

from comfy_api.latest import ComfyExtension, io
from typing_extensions import override

from .resolver import (
    PromptResolutionError,
    parse_json_prompt,
    resolve_dimensions,
)

MAX_REFERENCE_IMAGES = 10
_DEFAULT_MULTIPLE = 8


class PromptDimensionsFromLLM(io.ComfyNode):
    @classmethod
    def define_schema(cls) -> io.Schema:
        return io.Schema(
            node_id="PromptDimensionsFromLLM",
            display_name="Prompt & Dimensions from LLM",
            category="prompt/resolve",
            description=(
                "Resolves a diffusion prompt and target image size from an LLM "
                "JSON hint {rewritten_prompt, wh_ratio, ratio_follow}. Either "
                "wh_ratio (used with megapixels) or ratio_follow (an uploaded "
                "image's size) determines dimensions; at least one is required."
            ),
            inputs=[
                io.String.Input(
                    "llm_prompt",
                    multiline=True,
                    placeholder='{"rewritten_prompt": "...", "wh_ratio": "16:9"}',
                    tooltip="JSON hint generated by the LLM.",
                ),
                io.Float.Input(
                    "megapixels",
                    min=0.1,
                    max=16.0,
                    step=0.1,
                    default=1.0,
                    tooltip=(
                        "Target size in megapixels (0.1-16.0). Only used when "
                        "wh_ratio is provided; ignored when ratio_follow is used."
                    ),
                ),
                io.Int.Input(
                    "multiple",
                    min=8,
                    max=128,
                    step=4,
                    default=8,
                    tooltip=(
                        "Pixel grid that resolved width/height are rounded up to "
                        "(default 8). Only used when wh_ratio is provided."
                    ),
                ),
                io.Autogrow.Input(
                    "images",
                    template=io.Autogrow.TemplatePrefix(
                        io.Image.Input("image"),
                        prefix="image",
                        min=0,
                        max=MAX_REFERENCE_IMAGES,
                    ),
                    tooltip="Up to 10 reference images. ratio_follow can name one of "
                    "them (e.g. '<image1>') to reuse its exact size.",
                ),
            ],
            outputs=[
                io.String.Output("prompt"),
                io.Int.Output("width"),
                io.Int.Output("height"),
            ],
            search_aliases=["prompt", "dimensions", "ratio", "megapixel", "size"],
        )

    @classmethod
    def execute(cls, **kwargs) -> io.NodeOutput:
        try:
            llm_prompt: str = kwargs["llm_prompt"]
            megapixels: float = kwargs["megapixels"]
            multiple: int = kwargs.get("multiple", _DEFAULT_MULTIPLE)
            images = kwargs.get("images")
            data = parse_json_prompt(llm_prompt)
            prompt, width, height = resolve_dimensions(
                data, megapixels, images, multiple
            )
        except PromptResolutionError as exc:
            raise ValueError(str(exc)) from exc

        return io.NodeOutput(prompt, width, height)


class PromptDimensionsExtension(ComfyExtension):
    @override
    async def get_node_list(self) -> list[type[io.ComfyNode]]:
        return [PromptDimensionsFromLLM]


async def comfy_entrypoint() -> PromptDimensionsExtension:
    return PromptDimensionsExtension()
